<?php

use App\Models\BudgetPeriod;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Clear out the periods the nightly close loop invented.
     *
     * Until the fix that ships with this migration, `closePeriod` asked for a new
     * period anchored to the end of the budget's chain, and the scheduled command
     * called it for every period that had ever ended. Every run therefore pushed
     * the chain further out: 37,338 future periods across 376 live budgets, one
     * of them 6,165 rows deep and ending in the year 2143.
     *
     * They are not merely untidy. Loading them all is what killed
     * `budgets:generate-periods` with a fatal error every night from 2026-08-18,
     * so nothing has been generated or closed since, and their allocated and
     * carried-over amounts are noise nobody ever chose.
     *
     * Two are kept ahead of today because that is what the command maintains, so
     * the first run after this leaves the chain exactly as it finds it. Anything
     * holding budget transactions is left alone on principle - a future period
     * cannot have any today (verified: zero of the 37,338), but deleting one
     * cascades to its rows, and that is not a thing to be casual about.
     */
    public function up(): void
    {
        BudgetPeriod::query()
            ->where('start_date', '>', today())
            ->distinct()
            ->pluck('budget_id')
            ->each(function (string $budgetId): void {
                $keep = BudgetPeriod::query()
                    ->where('budget_id', $budgetId)
                    ->where('start_date', '>', today())
                    ->orderBy('start_date')
                    ->limit(2)
                    ->pluck('id');

                BudgetPeriod::query()
                    ->where('budget_id', $budgetId)
                    ->where('start_date', '>', today())
                    ->whereNotIn('id', $keep)
                    ->whereDoesntHave('budgetTransactions')
                    ->delete();
            });
    }

    public function down(): void
    {
        // One-off repair. The rows it deletes were generated by a bug and carry
        // nothing worth restoring; the command regenerates what is actually
        // needed on its next run.
    }
};
