<?php

return [
    'options' => [
        [
            'code' => 'USD',
            'name' => 'US Dollar',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'EUR',
            'name' => 'Euro',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'GBP',
            'name' => 'British Pound',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'JPY',
            'name' => 'Japanese Yen',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'CHF',
            'name' => 'Swiss Franc',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'CAD',
            'name' => 'Canadian Dollar',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'AUD',
            'name' => 'Australian Dollar',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'NZD',
            'name' => 'New Zealand Dollar',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'CNY',
            'name' => 'Chinese Yuan',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'INR',
            'name' => 'Indian Rupee',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'PKR',
            'name' => 'Pakistani Rupee',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'MXN',
            'name' => 'Mexican Peso',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'ARS',
            'name' => 'Argentine Peso',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'BOB',
            'name' => 'Bolivian Boliviano',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'CLP',
            'name' => 'Chilean Peso',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'PYG',
            'name' => 'Paraguayan Guarani',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'PEN',
            'name' => 'Peruvian Sol',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'UYU',
            'name' => 'Uruguayan Peso',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'VES',
            'name' => 'Venezuelan Bolívar',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'BRL',
            'name' => 'Brazilian Real',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'COP',
            'name' => 'Colombian Peso',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'DOP',
            'name' => 'Dominican Peso',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'SAR',
            'name' => 'Saudi Riyal',
            'allows_primary' => true,
            'allows_account' => true,
        ],
        [
            'code' => 'BTC',
            'name' => 'Bitcoin',
            'allows_primary' => false,
            'allows_account' => true,
        ],
    ],
];
