import { AiSparkleIcon } from '@/components/ui/ai-sparkle-icon';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { type AutomationRule } from '@/types/automation-rule';
import { __ } from '@/utils/i18n';

/**
 * A rule's title, prefixed with the shared AI sparkle when the rule itself was
 * generated by AI (origin === 'ai').
 */
export function AutomationRuleTitle({ rule }: { rule: AutomationRule }) {
    const isAiGenerated = rule.origin === 'ai';
    const label = __('Created by AI');

    return (
        <div className="flex items-center gap-1.5 font-medium">
            {isAiGenerated && (
                <TooltipProvider>
                    <Tooltip>
                        <TooltipTrigger asChild>
                            <span
                                className="inline-flex shrink-0"
                                aria-label={label}
                            >
                                <AiSparkleIcon className="h-3.5 w-3.5" />
                            </span>
                        </TooltipTrigger>
                        <TooltipContent>{label}</TooltipContent>
                    </Tooltip>
                </TooltipProvider>
            )}
            {rule.title}
        </div>
    );
}
