import { AiSparkleIcon } from '@/components/ui/ai-sparkle-icon';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { type AutomationRule } from '@/types/automation-rule';
import { __ } from '@/utils/i18n';

/**
 * A rule's title, prefixed with the shared AI sparkle when the rule came from AI
 * — either generated by auto-categorization (origin === 'ai') or learned from a
 * user's correction of an AI categorization (origin === 'correction').
 */
export function AutomationRuleTitle({ rule }: { rule: AutomationRule }) {
    const isAiRelated = rule.origin === 'ai' || rule.origin === 'correction';
    const label =
        rule.origin === 'correction'
            ? __('Learned from your correction')
            : __('Created by AI');

    return (
        <div className="flex items-center gap-1.5 font-medium">
            {isAiRelated && (
                <TooltipProvider>
                    <Tooltip>
                        <TooltipTrigger asChild>
                            <span
                                className="inline-flex shrink-0"
                                aria-label={label}
                            >
                                <AiSparkleIcon className="h-3.5 w-3.5" />
                            </span>
                        </TooltipTrigger>
                        <TooltipContent>{label}</TooltipContent>
                    </Tooltip>
                </TooltipProvider>
            )}
            {rule.title}
        </div>
    );
}
